import 'models.dart';

/// 离线法定货币目录。
///
/// 代码、数字码和 minor unit 基于 SIX 维护的 ISO 4217 List One（2026-01-01）；
/// 中英文名与符号基于 Unicode CLDR main（2026-08-18 快照）。排除了资金单位、
/// 贵金属、测试代码和“无货币”代码。目录更新流程见多币种设计文档。
abstract final class CurrencyCatalog {
  static const List<String> commonCodes = <String>[
    'CNY',
    'USD',
    'EUR',
    'JPY',
    'HKD',
    'GBP',
    'AUD',
    'CAD',
    'SGD',
    'KRW',
    'MOP',
    'TWD',
  ];

  static const List<CurrencyDefinition> all = <CurrencyDefinition>[
    CurrencyDefinition(
      code: 'AED',
      numericCode: '784',
      nameZh: '阿联酋迪拉姆',
      nameEn: 'United Arab Emirates Dirham',
      symbol: 'AED',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'AFN',
      numericCode: '971',
      nameZh: '阿富汗尼',
      nameEn: 'Afghan Afghani',
      symbol: 'AFN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ALL',
      numericCode: '008',
      nameZh: '阿尔巴尼亚列克',
      nameEn: 'Albanian Lek',
      symbol: 'ALL',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'AMD',
      numericCode: '051',
      nameZh: '亚美尼亚德拉姆',
      nameEn: 'Armenian Dram',
      symbol: 'AMD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'AOA',
      numericCode: '973',
      nameZh: '安哥拉宽扎',
      nameEn: 'Angolan Kwanza',
      symbol: 'AOA',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ARS',
      numericCode: '032',
      nameZh: '阿根廷比索',
      nameEn: 'Argentine Peso',
      symbol: 'ARS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'AUD',
      numericCode: '036',
      nameZh: '澳大利亚元',
      nameEn: 'Australian Dollar',
      symbol: 'A\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'AWG',
      numericCode: '533',
      nameZh: '阿鲁巴弗罗林',
      nameEn: 'Aruban Florin',
      symbol: 'AWG',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'AZN',
      numericCode: '944',
      nameZh: '阿塞拜疆马纳特',
      nameEn: 'Azerbaijani Manat',
      symbol: 'AZN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BAM',
      numericCode: '977',
      nameZh: '波斯尼亚-黑塞哥维那可兑换马克',
      nameEn: 'Bosnia-Herzegovina Convertible Mark',
      symbol: 'BAM',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BBD',
      numericCode: '052',
      nameZh: '巴巴多斯元',
      nameEn: 'Barbadian Dollar',
      symbol: 'BBD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BDT',
      numericCode: '050',
      nameZh: '孟加拉塔卡',
      nameEn: 'Bangladeshi Taka',
      symbol: 'BDT',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BHD',
      numericCode: '048',
      nameZh: '巴林第纳尔',
      nameEn: 'Bahraini Dinar',
      symbol: 'BHD',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'BIF',
      numericCode: '108',
      nameZh: '布隆迪法郎',
      nameEn: 'Burundian Franc',
      symbol: 'BIF',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'BMD',
      numericCode: '060',
      nameZh: '百慕大元',
      nameEn: 'Bermudan Dollar',
      symbol: 'BMD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BND',
      numericCode: '096',
      nameZh: '文莱元',
      nameEn: 'Brunei Dollar',
      symbol: 'BND',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BOB',
      numericCode: '068',
      nameZh: '玻利维亚诺',
      nameEn: 'Bolivian Boliviano',
      symbol: 'BOB',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BRL',
      numericCode: '986',
      nameZh: '巴西雷亚尔',
      nameEn: 'Brazilian Real',
      symbol: 'R\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BSD',
      numericCode: '044',
      nameZh: '巴哈马元',
      nameEn: 'Bahamian Dollar',
      symbol: 'BSD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BTN',
      numericCode: '064',
      nameZh: '不丹努尔特鲁姆',
      nameEn: 'Bhutanese Ngultrum',
      symbol: 'BTN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BWP',
      numericCode: '072',
      nameZh: '博茨瓦纳普拉',
      nameEn: 'Botswanan Pula',
      symbol: 'BWP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BYN',
      numericCode: '933',
      nameZh: '白俄罗斯卢布',
      nameEn: 'Belarusian Ruble',
      symbol: 'BYN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'BZD',
      numericCode: '084',
      nameZh: '伯利兹元',
      nameEn: 'Belize Dollar',
      symbol: 'BZD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CAD',
      numericCode: '124',
      nameZh: '加拿大元',
      nameEn: 'Canadian Dollar',
      symbol: 'CA\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CDF',
      numericCode: '976',
      nameZh: '刚果法郎',
      nameEn: 'Congolese Franc',
      symbol: 'CDF',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CHF',
      numericCode: '756',
      nameZh: '瑞士法郎',
      nameEn: 'Swiss Franc',
      symbol: 'CHF',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CLP',
      numericCode: '152',
      nameZh: '智利比索',
      nameEn: 'Chilean Peso',
      symbol: 'CLP',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'CNY',
      numericCode: '156',
      nameZh: '人民币',
      nameEn: 'Chinese Yuan',
      symbol: 'CN¥',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'COP',
      numericCode: '170',
      nameZh: '哥伦比亚比索',
      nameEn: 'Colombian Peso',
      symbol: 'COP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CRC',
      numericCode: '188',
      nameZh: '哥斯达黎加科朗',
      nameEn: 'Costa Rican Colón',
      symbol: 'CRC',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CUP',
      numericCode: '192',
      nameZh: '古巴比索',
      nameEn: 'Cuban Peso',
      symbol: 'CUP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CVE',
      numericCode: '132',
      nameZh: '佛得角埃斯库多',
      nameEn: 'Cape Verdean Escudo',
      symbol: 'CVE',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'CZK',
      numericCode: '203',
      nameZh: '捷克克朗',
      nameEn: 'Czech Koruna',
      symbol: 'CZK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'DJF',
      numericCode: '262',
      nameZh: '吉布提法郎',
      nameEn: 'Djiboutian Franc',
      symbol: 'DJF',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'DKK',
      numericCode: '208',
      nameZh: '丹麦克朗',
      nameEn: 'Danish Krone',
      symbol: 'DKK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'DOP',
      numericCode: '214',
      nameZh: '多米尼加比索',
      nameEn: 'Dominican Peso',
      symbol: 'DOP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'DZD',
      numericCode: '012',
      nameZh: '阿尔及利亚第纳尔',
      nameEn: 'Algerian Dinar',
      symbol: 'DZD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'EGP',
      numericCode: '818',
      nameZh: '埃及镑',
      nameEn: 'Egyptian Pound',
      symbol: 'EGP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ERN',
      numericCode: '232',
      nameZh: '厄立特里亚纳克法',
      nameEn: 'Eritrean Nakfa',
      symbol: 'ERN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ETB',
      numericCode: '230',
      nameZh: '埃塞俄比亚比尔',
      nameEn: 'Ethiopian Birr',
      symbol: 'ETB',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'EUR',
      numericCode: '978',
      nameZh: '欧元',
      nameEn: 'Euro',
      symbol: '€',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'FJD',
      numericCode: '242',
      nameZh: '斐济元',
      nameEn: 'Fijian Dollar',
      symbol: 'FJD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'FKP',
      numericCode: '238',
      nameZh: '福克兰群岛镑',
      nameEn: 'Falkland Islands Pound',
      symbol: 'FKP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GBP',
      numericCode: '826',
      nameZh: '英镑',
      nameEn: 'British Pound',
      symbol: '£',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GEL',
      numericCode: '981',
      nameZh: '格鲁吉亚拉里',
      nameEn: 'Georgian Lari',
      symbol: 'GEL',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GHS',
      numericCode: '936',
      nameZh: '加纳塞地',
      nameEn: 'Ghanaian Cedi',
      symbol: 'GHS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GIP',
      numericCode: '292',
      nameZh: '直布罗陀镑',
      nameEn: 'Gibraltar Pound',
      symbol: 'GIP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GMD',
      numericCode: '270',
      nameZh: '冈比亚达拉西',
      nameEn: 'Gambian Dalasi',
      symbol: 'GMD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GNF',
      numericCode: '324',
      nameZh: '几内亚法郎',
      nameEn: 'Guinean Franc',
      symbol: 'GNF',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'GTQ',
      numericCode: '320',
      nameZh: '危地马拉格查尔',
      nameEn: 'Guatemalan Quetzal',
      symbol: 'GTQ',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'GYD',
      numericCode: '328',
      nameZh: '圭亚那元',
      nameEn: 'Guyanaese Dollar',
      symbol: 'GYD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'HKD',
      numericCode: '344',
      nameZh: '港元',
      nameEn: 'Hong Kong Dollar',
      symbol: 'HK\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'HNL',
      numericCode: '340',
      nameZh: '洪都拉斯伦皮拉',
      nameEn: 'Honduran Lempira',
      symbol: 'HNL',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'HTG',
      numericCode: '332',
      nameZh: '海地古德',
      nameEn: 'Haitian Gourde',
      symbol: 'HTG',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'HUF',
      numericCode: '348',
      nameZh: '匈牙利福林',
      nameEn: 'Hungarian Forint',
      symbol: 'HUF',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'IDR',
      numericCode: '360',
      nameZh: '印度尼西亚卢比',
      nameEn: 'Indonesian Rupiah',
      symbol: 'IDR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ILS',
      numericCode: '376',
      nameZh: '以色列新谢克尔',
      nameEn: 'Israeli New Shekel',
      symbol: '₪',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'INR',
      numericCode: '356',
      nameZh: '印度卢比',
      nameEn: 'Indian Rupee',
      symbol: '₹',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'IQD',
      numericCode: '368',
      nameZh: '伊拉克第纳尔',
      nameEn: 'Iraqi Dinar',
      symbol: 'IQD',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'IRR',
      numericCode: '364',
      nameZh: '伊朗里亚尔',
      nameEn: 'Iranian Rial',
      symbol: 'IRR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ISK',
      numericCode: '352',
      nameZh: '冰岛克朗',
      nameEn: 'Icelandic Króna',
      symbol: 'ISK',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'JMD',
      numericCode: '388',
      nameZh: '牙买加元',
      nameEn: 'Jamaican Dollar',
      symbol: 'JMD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'JOD',
      numericCode: '400',
      nameZh: '约旦第纳尔',
      nameEn: 'Jordanian Dinar',
      symbol: 'JOD',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'JPY',
      numericCode: '392',
      nameZh: '日元',
      nameEn: 'Japanese Yen',
      symbol: '¥',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'KES',
      numericCode: '404',
      nameZh: '肯尼亚先令',
      nameEn: 'Kenyan Shilling',
      symbol: 'KES',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'KGS',
      numericCode: '417',
      nameZh: '吉尔吉斯斯坦索姆',
      nameEn: 'Kyrgyz Som',
      symbol: 'KGS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'KHR',
      numericCode: '116',
      nameZh: '柬埔寨瑞尔',
      nameEn: 'Cambodian Riel',
      symbol: 'KHR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'KMF',
      numericCode: '174',
      nameZh: '科摩罗法郎',
      nameEn: 'Comorian Franc',
      symbol: 'KMF',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'KPW',
      numericCode: '408',
      nameZh: '朝鲜元',
      nameEn: 'North Korean Won',
      symbol: 'KPW',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'KRW',
      numericCode: '410',
      nameZh: '韩元',
      nameEn: 'South Korean Won',
      symbol: '₩',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'KWD',
      numericCode: '414',
      nameZh: '科威特第纳尔',
      nameEn: 'Kuwaiti Dinar',
      symbol: 'KWD',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'KYD',
      numericCode: '136',
      nameZh: '开曼元',
      nameEn: 'Cayman Islands Dollar',
      symbol: 'KYD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'KZT',
      numericCode: '398',
      nameZh: '哈萨克斯坦坚戈',
      nameEn: 'Kazakhstani Tenge',
      symbol: 'KZT',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'LAK',
      numericCode: '418',
      nameZh: '老挝基普',
      nameEn: 'Laotian Kip',
      symbol: 'LAK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'LBP',
      numericCode: '422',
      nameZh: '黎巴嫩镑',
      nameEn: 'Lebanese Pound',
      symbol: 'LBP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'LKR',
      numericCode: '144',
      nameZh: '斯里兰卡卢比',
      nameEn: 'Sri Lankan Rupee',
      symbol: 'LKR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'LRD',
      numericCode: '430',
      nameZh: '利比里亚元',
      nameEn: 'Liberian Dollar',
      symbol: 'LRD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'LSL',
      numericCode: '426',
      nameZh: '莱索托洛蒂',
      nameEn: 'Lesotho Loti',
      symbol: 'LSL',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'LYD',
      numericCode: '434',
      nameZh: '利比亚第纳尔',
      nameEn: 'Libyan Dinar',
      symbol: 'LYD',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'MAD',
      numericCode: '504',
      nameZh: '摩洛哥迪拉姆',
      nameEn: 'Moroccan Dirham',
      symbol: 'MAD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MDL',
      numericCode: '498',
      nameZh: '摩尔多瓦列伊',
      nameEn: 'Moldovan Leu',
      symbol: 'MDL',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MGA',
      numericCode: '969',
      nameZh: '马达加斯加阿里亚里',
      nameEn: 'Malagasy Ariary',
      symbol: 'MGA',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MKD',
      numericCode: '807',
      nameZh: '马其顿第纳尔',
      nameEn: 'Macedonian Denar',
      symbol: 'MKD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MMK',
      numericCode: '104',
      nameZh: '缅甸元',
      nameEn: 'Myanmar Kyat',
      symbol: 'MMK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MNT',
      numericCode: '496',
      nameZh: '蒙古图格里克',
      nameEn: 'Mongolian Tugrik',
      symbol: 'MNT',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MOP',
      numericCode: '446',
      nameZh: '澳门币',
      nameEn: 'Macanese Pataca',
      symbol: 'MOP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MRU',
      numericCode: '929',
      nameZh: '毛里塔尼亚乌吉亚',
      nameEn: 'Mauritanian Ouguiya',
      symbol: 'MRU',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MUR',
      numericCode: '480',
      nameZh: '毛里求斯卢比',
      nameEn: 'Mauritian Rupee',
      symbol: 'MUR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MVR',
      numericCode: '462',
      nameZh: '马尔代夫卢菲亚',
      nameEn: 'Maldivian Rufiyaa',
      symbol: 'MVR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MWK',
      numericCode: '454',
      nameZh: '马拉维克瓦查',
      nameEn: 'Malawian Kwacha',
      symbol: 'MWK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MXN',
      numericCode: '484',
      nameZh: '墨西哥比索',
      nameEn: 'Mexican Peso',
      symbol: 'MX\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MYR',
      numericCode: '458',
      nameZh: '马来西亚林吉特',
      nameEn: 'Malaysian Ringgit',
      symbol: 'MYR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'MZN',
      numericCode: '943',
      nameZh: '莫桑比克美提卡',
      nameEn: 'Mozambican Metical',
      symbol: 'MZN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'NAD',
      numericCode: '516',
      nameZh: '纳米比亚元',
      nameEn: 'Namibian Dollar',
      symbol: 'NAD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'NGN',
      numericCode: '566',
      nameZh: '尼日利亚奈拉',
      nameEn: 'Nigerian Naira',
      symbol: 'NGN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'NIO',
      numericCode: '558',
      nameZh: '尼加拉瓜科多巴',
      nameEn: 'Nicaraguan Córdoba',
      symbol: 'NIO',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'NOK',
      numericCode: '578',
      nameZh: '挪威克朗',
      nameEn: 'Norwegian Krone',
      symbol: 'NOK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'NPR',
      numericCode: '524',
      nameZh: '尼泊尔卢比',
      nameEn: 'Nepalese Rupee',
      symbol: 'NPR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'NZD',
      numericCode: '554',
      nameZh: '新西兰元',
      nameEn: 'New Zealand Dollar',
      symbol: 'NZ\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'OMR',
      numericCode: '512',
      nameZh: '阿曼里亚尔',
      nameEn: 'Omani Rial',
      symbol: 'OMR',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'PAB',
      numericCode: '590',
      nameZh: '巴拿马巴波亚',
      nameEn: 'Panamanian Balboa',
      symbol: 'PAB',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'PEN',
      numericCode: '604',
      nameZh: '秘鲁索尔',
      nameEn: 'Peruvian Sol',
      symbol: 'PEN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'PGK',
      numericCode: '598',
      nameZh: '巴布亚新几内亚基那',
      nameEn: 'Papua New Guinean Kina',
      symbol: 'PGK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'PHP',
      numericCode: '608',
      nameZh: '菲律宾比索',
      nameEn: 'Philippine Peso',
      symbol: '₱',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'PKR',
      numericCode: '586',
      nameZh: '巴基斯坦卢比',
      nameEn: 'Pakistani Rupee',
      symbol: 'PKR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'PLN',
      numericCode: '985',
      nameZh: '波兰兹罗提',
      nameEn: 'Polish Zloty',
      symbol: 'PLN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'PYG',
      numericCode: '600',
      nameZh: '巴拉圭瓜拉尼',
      nameEn: 'Paraguayan Guarani',
      symbol: 'PYG',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'QAR',
      numericCode: '634',
      nameZh: '卡塔尔里亚尔',
      nameEn: 'Qatari Riyal',
      symbol: 'QAR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'RON',
      numericCode: '946',
      nameZh: '罗马尼亚列伊',
      nameEn: 'Romanian Leu',
      symbol: 'RON',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'RSD',
      numericCode: '941',
      nameZh: '塞尔维亚第纳尔',
      nameEn: 'Serbian Dinar',
      symbol: 'RSD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'RUB',
      numericCode: '643',
      nameZh: '俄罗斯卢布',
      nameEn: 'Russian Ruble',
      symbol: 'RUB',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'RWF',
      numericCode: '646',
      nameZh: '卢旺达法郎',
      nameEn: 'Rwandan Franc',
      symbol: 'RWF',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'SAR',
      numericCode: '682',
      nameZh: '沙特里亚尔',
      nameEn: 'Saudi Riyal',
      symbol: 'SAR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SBD',
      numericCode: '090',
      nameZh: '所罗门群岛元',
      nameEn: 'Solomon Islands Dollar',
      symbol: 'SBD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SCR',
      numericCode: '690',
      nameZh: '塞舌尔卢比',
      nameEn: 'Seychellois Rupee',
      symbol: 'SCR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SDG',
      numericCode: '938',
      nameZh: '苏丹镑',
      nameEn: 'Sudanese Pound',
      symbol: 'SDG',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SEK',
      numericCode: '752',
      nameZh: '瑞典克朗',
      nameEn: 'Swedish Krona',
      symbol: 'SEK',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SGD',
      numericCode: '702',
      nameZh: '新加坡元',
      nameEn: 'Singapore Dollar',
      symbol: 'SGD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SHP',
      numericCode: '654',
      nameZh: '圣赫勒拿群岛磅',
      nameEn: 'St. Helena Pound',
      symbol: 'SHP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SLE',
      numericCode: '925',
      nameZh: '塞拉利昂新利昂',
      nameEn: 'Sierra Leonean Leone',
      symbol: 'SLE',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SOS',
      numericCode: '706',
      nameZh: '索马里先令',
      nameEn: 'Somali Shilling',
      symbol: 'SOS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SRD',
      numericCode: '968',
      nameZh: '苏里南元',
      nameEn: 'Surinamese Dollar',
      symbol: 'SRD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SSP',
      numericCode: '728',
      nameZh: '南苏丹镑',
      nameEn: 'South Sudanese Pound',
      symbol: 'SSP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'STN',
      numericCode: '930',
      nameZh: '圣多美和普林西比多布拉',
      nameEn: 'São Tomé & Príncipe Dobra',
      symbol: 'STN',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SVC',
      numericCode: '222',
      nameZh: '萨尔瓦多科朗',
      nameEn: 'Salvadoran Colón',
      symbol: 'SVC',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SYP',
      numericCode: '760',
      nameZh: '叙利亚镑',
      nameEn: 'Syrian Pound',
      symbol: 'SYP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'SZL',
      numericCode: '748',
      nameZh: '斯威士兰里兰吉尼',
      nameEn: 'Swazi Lilangeni',
      symbol: 'SZL',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'THB',
      numericCode: '764',
      nameZh: '泰铢',
      nameEn: 'Thai Baht',
      symbol: 'THB',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TJS',
      numericCode: '972',
      nameZh: '塔吉克斯坦索莫尼',
      nameEn: 'Tajikistani Somoni',
      symbol: 'TJS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TMT',
      numericCode: '934',
      nameZh: '土库曼斯坦马纳特',
      nameEn: 'Turkmenistani Manat',
      symbol: 'TMT',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TND',
      numericCode: '788',
      nameZh: '突尼斯第纳尔',
      nameEn: 'Tunisian Dinar',
      symbol: 'TND',
      minorUnit: 3,
    ),
    CurrencyDefinition(
      code: 'TOP',
      numericCode: '776',
      nameZh: '汤加潘加',
      nameEn: 'Tongan Paʻanga',
      symbol: 'TOP',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TRY',
      numericCode: '949',
      nameZh: '土耳其里拉',
      nameEn: 'Turkish Lira',
      symbol: 'TRY',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TTD',
      numericCode: '780',
      nameZh: '特立尼达和多巴哥元',
      nameEn: 'Trinidad & Tobago Dollar',
      symbol: 'TTD',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TWD',
      numericCode: '901',
      nameZh: '新台币',
      nameEn: 'New Taiwan Dollar',
      symbol: 'NT\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'TZS',
      numericCode: '834',
      nameZh: '坦桑尼亚先令',
      nameEn: 'Tanzanian Shilling',
      symbol: 'TZS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'UAH',
      numericCode: '980',
      nameZh: '乌克兰格里夫纳',
      nameEn: 'Ukrainian Hryvnia',
      symbol: 'UAH',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'UGX',
      numericCode: '800',
      nameZh: '乌干达先令',
      nameEn: 'Ugandan Shilling',
      symbol: 'UGX',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'USD',
      numericCode: '840',
      nameZh: '美元',
      nameEn: 'US Dollar',
      symbol: '\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'UYU',
      numericCode: '858',
      nameZh: '乌拉圭比索',
      nameEn: 'Uruguayan Peso',
      symbol: 'UYU',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'UZS',
      numericCode: '860',
      nameZh: '乌兹别克斯坦苏姆',
      nameEn: 'Uzbekistani Som',
      symbol: 'UZS',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'VED',
      numericCode: '926',
      nameZh: '委内瑞拉主权币',
      nameEn: 'Bolívar Soberano',
      symbol: 'VED',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'VES',
      numericCode: '928',
      nameZh: '委内瑞拉玻利瓦尔',
      nameEn: 'Venezuelan Bolívar',
      symbol: 'VES',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'VND',
      numericCode: '704',
      nameZh: '越南盾',
      nameEn: 'Vietnamese Dong',
      symbol: '₫',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'VUV',
      numericCode: '548',
      nameZh: '瓦努阿图瓦图',
      nameEn: 'Vanuatu Vatu',
      symbol: 'VUV',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'WST',
      numericCode: '882',
      nameZh: '萨摩亚塔拉',
      nameEn: 'Samoan Tala',
      symbol: 'WST',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'XAF',
      numericCode: '950',
      nameZh: '中非法郎',
      nameEn: 'Central African CFA Franc',
      symbol: 'FCFA',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'XCD',
      numericCode: '951',
      nameZh: '东加勒比元',
      nameEn: 'East Caribbean Dollar',
      symbol: 'EC\$',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'XCG',
      numericCode: '532',
      nameZh: '加勒比盾',
      nameEn: 'Caribbean guilder',
      symbol: 'Cg.',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'XOF',
      numericCode: '952',
      nameZh: '西非法郎',
      nameEn: 'West African CFA Franc',
      symbol: 'F CFA',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'XPF',
      numericCode: '953',
      nameZh: '太平洋法郎',
      nameEn: 'CFP Franc',
      symbol: 'CFPF',
      minorUnit: 0,
    ),
    CurrencyDefinition(
      code: 'YER',
      numericCode: '886',
      nameZh: '也门里亚尔',
      nameEn: 'Yemeni Rial',
      symbol: 'YER',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ZAR',
      numericCode: '710',
      nameZh: '南非兰特',
      nameEn: 'South African Rand',
      symbol: 'ZAR',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ZMW',
      numericCode: '967',
      nameZh: '赞比亚克瓦查',
      nameEn: 'Zambian Kwacha',
      symbol: 'ZMW',
      minorUnit: 2,
    ),
    CurrencyDefinition(
      code: 'ZWG',
      numericCode: '924',
      nameZh: '津巴布韦金元',
      nameEn: 'Zimbabwean Gold',
      symbol: 'ZWG',
      minorUnit: 2,
    ),
  ];

  static final Map<String, CurrencyDefinition> _byCode =
      <String, CurrencyDefinition>{for (final item in all) item.code: item};

  static CurrencyDefinition? find(String? code) {
    if (code == null) return null;
    return _byCode[code.trim().toUpperCase()];
  }

  static CurrencyDefinition require(String code) {
    final currency = find(code);
    if (currency == null) {
      throw ArgumentError.value(code, 'code', 'Unsupported currency code');
    }
    return currency;
  }

  static bool isSupported(String? code) => find(code) != null;

  static List<CurrencyDefinition> search(String query) {
    final normalized = query.trim().toLowerCase();
    final matches = normalized.isEmpty
        ? List<CurrencyDefinition>.of(all)
        : all
              .where(
                (item) =>
                    item.code.toLowerCase().contains(normalized) ||
                    item.numericCode.contains(normalized) ||
                    item.nameZh.toLowerCase().contains(normalized) ||
                    item.nameEn.toLowerCase().contains(normalized) ||
                    item.symbol.toLowerCase().contains(normalized),
              )
              .toList();
    final commonRank = <String, int>{
      for (final item in commonCodes.indexed) item.$2: item.$1,
    };
    matches.sort((a, b) {
      final aRank = commonRank[a.code];
      final bRank = commonRank[b.code];
      if (aRank != null || bRank != null) {
        return (aRank ?? commonCodes.length).compareTo(
          bRank ?? commonCodes.length,
        );
      }
      return a.code.compareTo(b.code);
    });
    return matches;
  }
}
